# Generated by Django 5.0.1 on 2024-06-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=15)),
                ("place", models.CharField(max_length=30)),
                (
                    "choose",
                    models.CharField(
                        choices=[
                            ("site plan", "Site Plan"),
                            ("interiors design", "Interiors Design"),
                            ("renovation", "Renovation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("squre", models.CharField(max_length=10)),
                ("message", models.TextField()),
            ],
        ),
    ]
